products_data = [
    {
        "id": 1,
        "name": "Premium Fried Groundnuts",
        "price": 250,
        "image": "/premium_fried_groundnuts.png",
        "rating": 5,
        "category": "Fried",
        "description": "Crispy, golden-brown fried groundnuts seasoned to perfection. Made from the finest locally sourced nuts, fried in fresh vegetable oil for that distinct crunch.",
    },
    {
        "id": 2,
        "name": "Roasted Salted Peanuts",
        "price": 240,
        "image": "/roasted_salted_peanuts.png",
        "rating": 4,
        "category": "Roasted",
        "description": "Slow-roasted peanuts with a touch of sea salt. Dry roasted to preserve natural oils and flavor, making them a healthy and delicious snack.",
    },
    {
        "id": 3,
        "name": "Pure Natural Honey (500g)",
        "price": 800,
        "image": "/honey_pure_natural.png",
        "rating": 5,
        "category": "Honey",
        "description": "100% organic raw honey harvested from local forests. Unprocessed and unpasteurized to retain all natural enzymes, pollen, and antioxidants.",
    },
    {
        "id": 4,
        "name": "Smooth Peanut Butter",
        "price": 450,
        "image": "/smooth_peanut_butter.png",
        "rating": 5,
        "category": "Butter",
        "description": "Creamy, smooth peanut butter with no added preservatives. Made from premium roasted peanuts, perfect for spreading on bread or adding to smoothies.",
    },
    {
        "id": 5,
        "name": "Crunchy Peanut Butter",
        "price": 450,
        "image": "/peanut_crunchy_butter.png",
        "rating": 4,
        "category": "Butter",
        "description": "Rich peanut butter with real crunchy nut pieces. Offers a delightful texture and intense peanut flavor for those who like a bit of bite.",
    },
    {
        "id": 6,
        "name": "Spicy Fried Groundnuts",
        "price": 260,
        "image": "/spicy_fried_groundnuts.png",
        "rating": 5,
        "category": "Fried",
        "description": "Fried groundnuts with a kick of chili and spices. A perfect blend of heat and savory crunch for spice lovers.",
    },
    {
        "id": 7,
        "name": "Honey Roasted Peanuts",
        "price": 300,
        "image": "/honey_roasted_peanuts.png",
        "rating": 5,
        "category": "Roasted",
        "description": "Sweet and savory honey roasted peanuts. Glazed with our pure natural honey and roasted to golden perfection.",
    },
    {
        "id": 8,
        "name": "Raw Organic Honey (1kg)",
        "price": 1500,
        "image": "/raw_organic_honey.png",
        "rating": 5,
        "category": "Honey",
        "description": "Large jar of our signature raw organic honey. Great value for families and honey enthusiasts.",
    },
    {
        "id": 9,
        "name": "Chocolate Peanut Butter",
        "price": 550,
        "image": "/chocolate_peanut_butter.png",
        "rating": 4,
        "category": "Butter",
        "description": "Decadent blend of roasted peanuts and cocoa. A healthy treat that tastes like dessert.",
    },
]